language: node_js
node_js:
  - 12

services:
  - docker

script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed lbcostadev/udagram-api-feed:v1
  - docker tag udagram-api-user lbcostadev/udagram-api-user:v1
  - docker tag udagram-frontend lbcostadev/udagram-frontend:v1
  - docker tag reverseproxy lbcostadev/reverseproxy:v1

after_success:
  # Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lbcostadev/udagram-api-feed:v1
  - docker push lbcostadev/udagram-api-user:v1
  - docker push lbcostadev/udagram-frontend:v1
  - docker push lbcostadev/reverseproxy:v1